### ISSUE TITLE
Errors when using DDG Search, even after updating to latest version

### ISSUE THREAD

**Issue by scooter7** [deedy5/duckduckgo_search#133]
Hi,

On https://samfordddgpy-afze9ectc8p7xkcwpmkry9.streamlit.app/ , I'm using duckduckgo_search and have been successfully for months. 

However, for the past two days, I've been receiving the following traceback errors when running the app:

Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/mount/src/web/samfordddg.py", line 4, in <module>
    CCBCommonDDG.setup_form("https://www.samford.edu/", "Find out about Samford! You can ask about our programs, admissions, life on campus, etc.", "", "", "", "https://raw.githubusercontent.com/scooter7/scooter7.github.io/main/images/samford/Bulldog-Social-Icon.png", "https://raw.githubusercontent.com/scooter7/scooter7.github.io/main/images/samford/Bulldog-Social-Icon.png", True)
  File "/mount/src/web/CCBCommonDDG.py", line 146, in setup_form
    response = chatbot(domain, input_text, full_name, email)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount/src/web/CCBCommonDDG.py", line 67, in chatbot
    response = r if r != False else search_agent.run("site:" + domain + " " + prompt)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 440, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 987, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 850, in _take_next_step
    observation = tool.run(
                  ^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/base.py", line 320, in run
    raise e
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/base.py", line 292, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/ddg_search/tool.py", line 35, in _run
    return self.api_wrapper.run(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/utilities/duckduckgo_search.py", line 63, in run
    snippets = self.get_snippets(query)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/utilities/duckduckgo_search.py", line 55, in get_snippets
    for i, res in enumerate(results, 1):
  File "/home/adminuser/venv/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 150, in text
    yield from self._text_api(keywords, region, safesearch, timelimit)
  File "/home/adminuser/venv/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 203, in _text_api
    resp = self._get_url(
           ^^^^^^^^^^^^^^
  File "/home/adminuser/venv/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 89, in _get_url
    raise ex
  File "/home/adminuser/venv/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 82, in _get_url
    raise httpx._exceptions.HTTPError("")
httpx.HTTPError

Do you know what is happening with this error?

Thanks!

**Comment by deedy5** [comment]
Hi.
Try upgrading to the latest version (v3.9.5).

**Comment by scooter7** [comment]
Hi, @deedy5 , I did that and got the same error.

Thanks!

**Comment by deedy5** [comment]
You may not have updated the package in venv.
version must be 3.9.5
```python3
# activate venv
source /home/adminuser/venv/bin/activate
# check duckduckgo_version
ddgs version
# update duckduckgo_search
pip install -U duckduckgo_search
```

**Comment by scooter7** [comment]
Hi, The app is hosted on streamlit cloud.

**Comment by GianfrancoCorrea** [comment]
Tengo el mismo problema aquí, creé un proyecto hoy y funcionaba bien haciendo búsquedas asíncronas, pero ahora falla con todas las búsquedas con ese error.
ddgs version: 3.9.5
running in local streamlit, (i think the same error is happening in chainlit)

**Comment by scooter7** [comment]
On streamlit cloud, I resolved several dependency issues and now get:

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/web/samfordddg.py", line 4, in <module>

    CCBCommonDDG.setup_form("https://www.samford.edu", "Find out about Samford! You can ask about our programs, admissions, life on campus, etc.", "", "", "", "https://raw.githubusercontent.com/scooter7/scooter7.github.io/main/images/samford/Bulldog-Social-Icon.png", "https://raw.githubusercontent.com/scooter7/scooter7.github.io/main/images/samford/Bulldog-Social-Icon.png", True)

  File "/mount/src/web/CCBCommonDDG.py", line 146, in setup_form

    response = chatbot(domain, input_text, full_name, email)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/web/CCBCommonDDG.py", line 67, in chatbot

    response = r if r != False else search_agent.run("site:" + domain + " " + prompt)

                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 440, in run

    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 243, in __call__

    raise e

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 237, in __call__

    self._call(inputs, run_manager=run_manager)

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 987, in _call

    next_step_output = self._take_next_step(

                       ^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/agents/agent.py", line 850, in _take_next_step

    observation = tool.run(

                  ^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/base.py", line 320, in run

    raise e

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/base.py", line 292, in run

    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/tools/ddg_search/tool.py", line 35, in _run

    return self.api_wrapper.run(query)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/utilities/duckduckgo_search.py", line 63, in run

    snippets = self.get_snippets(query)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/langchain/utilities/duckduckgo_search.py", line 45, in get_snippets

    with DDGS() as ddgs:

         ^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 35, in __init__

    self._client = httpx.Client(headers=headers, proxies=proxies, timeout=timeout, http2=True)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/httpx/_client.py", line 672, in __init__

    self._transport = self._init_transport(

                      ^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/httpx/_client.py", line 720, in _init_transport

    return HTTPTransport(

           ^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 136, in __init__

    self._pool = httpcore.ConnectionPool(

                 ^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

**Comment by deedy5** [comment]
I can't reproduce the problem, all tests pass.
Also local streamlit works as well.

Try using a proxy, maybe your cloud provider gives the same external ip for different applications.

Also if you create an issue, add the code so I can reproduce the problem.
