### ISSUE TITLE
_get_url() https://duckduckgo.com KeyError: 'https'

### ISSUE THREAD

**Issue by Anonymous-Knight** [deedy5/duckduckgo_search#161]
**Before you open an issue:**
1. Make sure you have the latest version installed. Check: `ddgs version`. Update: `pip install -U duckduckgo_search`
3. Try reinstalling the library: `pip install -I duckduckgo_search`
4. Make sure the site https://duckduckgo.com is accessible in your browser
5. Try using a proxy. The site may block ip for a while.

**Describe the bug**
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com KeyError: 'https'

**Debug log**
Traceback (most recent call last):
  File "/home/zhouzhenyu05/test/kwaipilot-tool-server/src/kuaishou/search/search.py", line 111, in <module>
    results = web_search('什么是okr')
  File "/home/zhouzhenyu05/test/kwaipilot-tool-server/src/kuaishou/search/search.py", line 94, in web_search
    google_result = google_search(query)
  File "/home/zhouzhenyu05/test/kwaipilot-tool-server/src/kuaishou/search/search.py", line 52, in google_search
    results = [SearchResult(title=item['title'],url=item['href'],content=item['body']) for item in search_results]
  File "/home/zhouzhenyu05/test/kwaipilot-tool-server/src/kuaishou/search/search.py", line 52, in <listcomp>
    results = [SearchResult(title=item['title'],url=item['href'],content=item['body']) for item in search_results]
  File "/opt/conda/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 91, in text
    for i, result in enumerate(results, start=1):
  File "/opt/conda/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 119, in _text_api
    vqd = self._get_vqd(keywords)
  File "/opt/conda/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 54, in _get_vqd
    resp = self._get_url("POST", "https://duckduckgo.com", data={"q": keywords})
  File "/opt/conda/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 50, in _get_url
    raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).__name__}: {ex}")
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com KeyError: 'https'

**Specify this information**
 - Linux x86_64
 - duckduckgo_search V4.1.0

**Comment by Anonymous-Knight** [comment]
I've tried using a proxy and the site https://duckduckgo.com/ is accessible in my browser.

**Comment by deedy5** [comment]
Hi.
I think there's a problem with the proxy syntax.
Show me the code.

**Comment by Anonymous-Knight** [comment]
Hi. 
![截屏2023-12-18 14 10 57](https://github.com/deedy5/duckduckgo_search/assets/23411723/2a477dc7-1172-4172-9f0e-a8ee9e9bcca3)

**Comment by deedy5** [comment]
What's proxy type showing?
```python
print(proxies)
print(type(proxies))
```

**Comment by Anonymous-Knight** [comment]
It is a dict
![截屏2023-12-18 14 43 43](https://github.com/deedy5/duckduckgo_search/assets/23411723/a27ab5fa-a1ba-48ae-ba0b-d82086ad735d)

**Comment by deedy5** [comment]
The problem in proxy syntax. Since v4.0.0 `duckduckgo_search` uses `curl-cffi`.

`httpx`: 
```python
proxies = {
    "http://": "http://localhost:8030",
    "https://": "http://localhost:8031",
}
```
`curl-cffi`:
```python
 proxies = {
    "http": "http://localhost:8030",
    "https": "http://localhost:8031",
}
```

**Comment by Anonymous-Knight** [comment]
Thanks for your time! Help a lot.
