### ISSUE TITLE
conflicting event loops and threads while running with flask-socketio

### ISSUE THREAD

**Issue by ARajgor** [deedy5/duckduckgo_search#206]
I'm facing a runtime error while running the duckduckgo_search module. 

Here's what I already tried
- remove the agent from running in the extra thread and run it to the main thread
- spawn an extra thread to handle Duckduckgo
- use asyncio to get the current loop and integrate the duckduckgo task in it.
- use AsyncDDGS and await for all functions.

I tried all of the above methods and different things but none of them are working. It keeps getting the same kind of error of conflicting loops and threads.

How can I solve this???

Exception error log
```
Exception in thread Thread-11 (run_forever):
Traceback (most recent call last):
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 596, in run_forever
    self._check_running()
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 590, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
```

Now I explain how my project is set. workflow is from main.py -> agent.py -> search.py

```
project structure :
|-main.py
|-src
  |-agent
    |-agent.py
    |-socket_instance.py
  |-browser
    |-search.py
```

main.py
```
import eventlet
eventlet.monkey_patch()

from src.socket_instance import socketio
app = Flask(__name__)
socketio.init_app(app)

@socketio.on('user-message')
def handle_message(data):   
  agent = Agent(base_model=base_model, search_engine=search_engine)

  if action == 'execute_agent':
        # agent.execute(message, project_name, search_engine)
        thread = Thread(target=lambda: agent.execute(message, project_name, search_engine))
        thread.start()


if __name__ == "__main__":
    socketio.run(app, debug=False, port=1337, host="0.0.0.0")
```

socket_instance.py
```
from flask_socketio import SocketIO
socketio = SocketIO(cors_allowed_origins="*", async_mode="eventlet")
```

agent.py
```
from src.browser.search import  DuckDuckGoSearch

class Agent:

    def search_queries(self, queries: list, project_name: str, engine: str) -> dict:
        elif engine == "duckduckgo":
            web_search = DuckDuckGoSearch()
        for query in queries:
            query = query.strip().lower()
            web_search.search(query)

            link = web_search.get_first_link()
       .
       .


    def execute(self, prompt: str, project_name_from_user: str = None, engine: str = None) -> str:
        if queries and len(queries) > 0:
            search_results = self.search_queries(queries, project_name, engine)

```

search.py
```
class DuckDuckGoSearch:
    def __init__(self):
        self.query_result = None

    def search(self, query):
        from duckduckgo_search import DDGS
        try:
            self.query_result = DDGS().text(query, max_results=5, region="us")
            print(self.query_result)

        except Exception as err:
            print(err)

    def get_first_link(self):
        if self.query_result:
            return self.query_result[0]["href"]
        else:
            return None

```

**Comment by deedy5** [comment]
How can I reproduce the error?

**Comment by ARajgor** [comment]
it is quite complicated. I don't know how to reproduce that's why I mention necessary code files.
I'm implementing duckduckgo search in this, https://github.com/stitionai/devika/pull/24

my current solution is to get raw functions from the duckduckgo_search library and custom implement it.

```
class DuckDuckGoSearch:
    """DuckDuckGo search engine class.
    methods are inherited from the duckduckgo_search package.
    do not change the methods.

    currently, the package is not working with our current setup.
    """
    def __init__(self):
        from curl_cffi import requests as curl_requests
        self.query_result = None
        self.asession = curl_requests.Session(impersonate="chrome", allow_redirects=False)
        self.asession.headers["Referer"] = "https://duckduckgo.com/"

    def _get_url(self, method, url, data):
        try:
            resp = self.asession.request(method, url, data=data)
        except Exception as error:
            if "timeout" in str(error).lower():
                raise TimeoutError("Duckduckgo timed out error")
        if resp.status_code == 200:
            return resp.content
        if resp.status_code == (202, 301, 403):
            raise Exception(f"Error: {resp.status_code} rate limit error")

    def duck(self, query):
        resp = self._get_url("POST", "https://duckduckgo.com/", data={"q": query})
        vqd = self.extract_vqd(resp)

        params = {"q": query, "kl": 'en-us', "p": "1", "s": "0", "df": "", "vqd": vqd, "ex": ""}
        resp = self._get_url("GET", "https://links.duckduckgo.com/d.js", params)
        page_data = self.text_extract_json(resp)

        results = []
        for row in page_data:
            href = row.get("u")
            if href and href != f"http://www.google.com/search?q={query}":
                body = self.normalize(row["a"])
                if body:
                    result = {
                        "title": self.normalize(row["t"]),
                        "href": self.normalize_url(href),
                        "body": self.normalize(row["a"]),
                    }
                    results.append(result)

        self.query_result = results

    def search(self, query):
        self.duck(query)

    def get_first_link(self):
        return self.query_result[0]["href"]

    @staticmethod
    def extract_vqd(html_bytes: bytes) -> str:
        patterns = [(b'vqd="', 5, b'"'), (b"vqd=", 4, b"&"), (b"vqd='", 5, b"'")]
        for start_pattern, offset, end_pattern in patterns:
            try:
                start = html_bytes.index(start_pattern) + offset
                end = html_bytes.index(end_pattern, start)
                return html_bytes[start:end].decode()
            except ValueError:
                continue

    @staticmethod
    def text_extract_json(html_bytes):
        try:
            start = html_bytes.index(b"DDG.pageLayout.load('d',") + 24
            end = html_bytes.index(b");DDG.duckbar.load(", start)
            return orjson.loads(html_bytes[start:end])
        except Exception as ex:
            print(f"Error extracting JSON: {type(ex).__name__}: {ex}")

    @staticmethod
    def normalize_url(url: str) -> str:
        return unquote(url.replace(" ", "+")) if url else ""

    @staticmethod
    def normalize(raw_html: str) -> str:
        return unescape(re.sub("<.*?>", "", raw_html)) if raw_html else ""

```

**Comment by deedy5** [comment]
The files above contain many errors and the code will not run. 
After correcting the code I was able to run it, but I didn't see any of the errors you mention.

That's why my question is relevant: how can I reproduce the error?
You can show me any of your solutions from those mentioned.

>Here's what I already tried

>    remove the agent from running in the extra thread and run it to the main thread
    spawn an extra thread to handle Duckduckgo
    use asyncio to get the current loop and integrate the duckduckgo task in it.
    use AsyncDDGS and await for all functions.
    create a new new loop in new thread
