### ISSUE TITLE
`RatelimitException` Not Consistently Raised

### ISSUE THREAD

**Issue by Umpire2018** [deedy5/duckduckgo_search#265]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [ ] I tried using a proxy (the site may block ip for a while)
      
**Describe the bug**

When using library for batch asynchronous search, it was observed that some requests with status code 202 do not raise the expected `RatelimitException`. Specifically:

- The logs show multiple requests returning status code 202.
- Only the first request with a 202 status code raises a RatelimitException, while subsequent requests with the same status code do not raise any exception.
This inconsistent behavior may cause users to miss rate-limiting issues in batch processing scenarios and complicates error handling logic.

**Observed Behavior**
```python
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=quantum+computing 200 25603
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=ocean 200 19405
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=sun 200 20204
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=artificial+intelligence 200 26757
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=mountain 200 25141
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=earth 200 26290
2024-12-14 17:48:08 - duckduckgo_search.DDGS - DEBUG - _get_url() https://duckduckgo.com/?q=moon 200 26545
2024-12-14 17:48:09 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=quantum+computing&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-31536039448539333706229452435378667451&bing_market=wt-WT&ex=-1 202 539
Traceback (most recent call last):
  File "/home/test/AgentFactory/test.py", line 183, in <module>
    asyncio.run(main())
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/test.py", line 164, in main
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/test.py", line 158, in aget_results
    results = await AsyncDDGS(timeout=5).atext(word)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 87, in atext
    result = await self._loop.run_in_executor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search.py", line 244, in text
    results = self._text_api(keywords, region, safesearch, timelimit, max_results)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search.py", line 331, in _text_api
    raise e
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search.py", line 328, in _text_api
    for r in self._executor.map(_text_api_page, slist):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/test/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search.py", line 306, in _text_api_page
    resp_content = self._get_url("GET", "https://links.duckduckgo.com/d.js", params=payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/AgentFactory/.venv/lib/python3.12/site-packages/duckduckgo_search/duckduckgo_search.py", line 134, in _get_url
    raise RatelimitException(f"{resp.url} {resp.status_code} Ratelimit")
duckduckgo_search.exceptions.RatelimitException: https://links.duckduckgo.com/d.js?q=quantum+computing&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-31536039448539333706229452435378667451&bing_market=wt-WT&ex=-1 202 Ratelimit
2024-12-14 17:48:09 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=sun&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-54438243966689648352836212504470799696&bing_market=wt-WT&ex=-1 202 492
2024-12-14 17:48:09 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=ocean&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-179379280803971599097693887696570581892&bing_market=wt-WT&ex=-1 202 492
2024-12-14 17:48:10 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=artificial+intelligence&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-286035566661038128320050947264261489697&bing_market=wt-WT&ex=-1 202 547
2024-12-14 17:48:10 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=mountain&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-62871713181910789246604857598050694174&bing_market=wt-WT&ex=-1 202 530
2024-12-14 17:48:10 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=earth&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-93075543948355672287541295405846351445&bing_market=wt-WT&ex=-1 202 490
2024-12-14 17:48:10 - duckduckgo_search.DDGS - DEBUG - _get_url() https://links.duckduckgo.com/d.js?q=moon&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-231849354880133823671061340834625997836&bing_market=wt-WT&ex=-1 202 489
```

**Steps to reproduce the problem:**
```python
import asyncio

from duckduckgo_search import AsyncDDGS

async def aget_results(word):
    results = await AsyncDDGS(timeout=5).atext(word)
    return results

async def main():
    words = ["sun", "earth", "moon", "ocean", "mountain","artificial intelligence", "quantum computing"]
    tasks = [aget_results(w) for w in words]
    results = await asyncio.gather(*tasks)
    print(results)

if __name__ == "__main__":
    import logging

    ddgs_logger = logging.getLogger("duckduckgo_search.DDGS")
    ddgs_logger.setLevel(logging.DEBUG)
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
    fmt="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    )
    console_handler.setFormatter(formatter)

    ddgs_logger.addHandler(console_handler)

    asyncio.run(main())
```
**Expected Behavior**
All requests returning a 202 status code should consistently raise a RatelimitException.

**Specify this information**

 - OS `Debian GNU/Linux 12 (bookworm)`
 - environment `python 3.12.7`
 - duckduckgo_search version `6.4.1`

**Comment by Umpire2018** [comment]
**Analysis**

The `_get_url` method is expected to:
1. Set the `_exception_event` upon encountering an error (e.g., `RatelimitException` or a timeout).
2. Raise an appropriate exception (e.g., `RatelimitException` for a `202` status or `DuckDuckGoSearchException` for other errors).

However, during execution, the following issues are observed:
- When a `202` status code is encountered for the first time, `_exception_event` is correctly set, and a `RatelimitException` is raised as expected.
- For subsequent requests returning a `202` status code, the `_exception_event` remains set, but no further exceptions are raised. Instead, these requests proceed as if no error occurred, which is inconsistent with the intended behavior.
