### ISSUE TITLE
return None using demo

### ISSUE THREAD

**Issue by Undertone0809** [deedy5/duckduckgo_search#61]
I got None when I use the following demo. I try to changed different network and also tried to use proxy, but all failed. I wonder why.

```python
from duckduckgo_search import ddg

keywords = 'Bella Ciao'
results = ddg(keywords, region='wt-wt', safesearch='Off', time='y')
print(results)

```

**Comment by Undertone0809** [comment]
2.9.5

**Comment by deedy5** [comment]
Please run this and show the result
```python3
import logging
from duckduckgo_search import ddg

logging.basicConfig(level=logging.DEBUG)

keywords = 'Bella Ciao'
results = ddg(keywords, region='wt-wt', safesearch='Off', time='y')
print(results)
```

**Comment by Undertone0809** [comment]
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
DEBUG:urllib3.connectionpool:https://duckduckgo.com:443 "POST / HTTP/1.1" 200 None
ERROR:duckduckgo_search.utils:
Traceback (most recent call last):
  File "C:\Users\86132\AppData\Roaming\Python\Python310\site-packages\duckduckgo_search\utils.py", line 51, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
ValueError: subsection not found
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
DEBUG:urllib3.connectionpool:https://duckduckgo.com:443 "POST / HTTP/1.1" 200 None
ERROR:duckduckgo_search.utils:
Traceback (most recent call last):
  File "C:\Users\86132\AppData\Roaming\Python\Python310\site-packages\duckduckgo_search\utils.py", line 51, in _get_vqd
    vqd_index_start = resp.content.index(b"vqd='") + 5
ValueError: subsection not found
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
```

**Comment by Undertone0809** [comment]
Do you also return None when you test?

**Comment by deedy5** [comment]
I checked the code, you have an old version.

It should be like this: https://github.com/deedy5/duckduckgo_search/blob/90a2cd7f5951b4dc5373753d65343b75a75293ba/duckduckgo_search/utils.py#LL51C13-L51C17

Reinstall the package.
```pip install -I duckduckgo_search```

**Comment by Undertone0809** [comment]
Thank a lot! The problem may be that I have several different Pythons and the version I used was older.

**Comment by bable631** [comment]
I am having the same issue as OP, but the command you gave to reinstall did not fix the issue. I have version 2.9.5 and am on python 3.10

**Comment by deedy5** [comment]
https://github.com/deedy5/duckduckgo_search/issues/61#issuecomment-1548065763

**Comment by bable631** [comment]
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
INFO:duckduckgo_search.utils:_get_vqd() keywords=Bella Ciao ConnectTimeout HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f33e6681810>, 'Connection to duckduckgo.com timed out. (connect timeout=10)'))
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
INFO:duckduckgo_search.utils:_get_vqd() keywords=Bella Ciao ConnectTimeout HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f33e6682aa0>, 'Connection to duckduckgo.com timed out. (connect timeout=10)'))
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
None
```DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
INFO:duckduckgo_search.utils:_get_vqd() keywords=Bella Ciao ConnectTimeout HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f33e6681810>, 'Connection to duckduckgo.com timed out. (connect timeout=10)'))
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): duckduckgo.com:443
INFO:duckduckgo_search.utils:_get_vqd() keywords=Bella Ciao ConnectTimeout HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f33e6682aa0>, 'Connection to duckduckgo.com timed out. (connect timeout=10)'))
WARNING:duckduckgo_search.utils:keywords=Bella Ciao. _get_vqd() is None, refreshing SESSION
None

**Comment by Undertone0809** [comment]
I'm sorry but I got the same problem in `v3.2.0`. I got `None` when I using demo code. I've had success getting the result, but most of the time I've returned None when I use `DDGS().text()`

**Comment by deedy5** [comment]
Something has changed in the api again, I'm trying to figure it out. After a certain number of successful responses api starts to give responses with status code 202, after which the status code changes to 418 with ip blocking for 60 seconds.
This only applies to DDGS().text().

**Comment by elwo412** [comment]
Can confirm I am seeing the same with 3.2.0. Examining the debug logs, every request is met with a 202 response.

**Comment by naquoc** [comment]
I confirm that I faced the same problems when using v3.2.0, `DDGS().text()` returns nothing.

**Comment by anton1700** [comment]
I have the same problem with V3.3.0 using the provided example.
If the keywords value is 'Bella Ciao' it produce an error,  
If the keywords value is 'Bella Ciao filetype:pdf' there's no error


```
from duckduckgo_search import DDGS

ddgs = DDGS()

# keywords = 'Bella Ciao'
keywords = 'Bella Ciao filetype:pdf'

ddgs_text_gen = ddgs.text(keywords, region='wt-wt', safesearch='Off', timelimit='y')
for r in ddgs_text_gen:
	print(r)



```

**Comment by deedy5** [comment]
I can't reproduce the problem right now. Everything works.
