### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by int75** [deedy5/duckduckgo_search#72]
I have ran both commands successfully.
```pip install -I duckduckgo_search```
and 
```pip install -I duckduckgo_search --break-system-packages```
commands

**Describe the bug**
When the test program is executed the system throws an error.
```
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
Using the example code provided below:
```
from duckduckgo_search import DDGS

ddgs = DDGS()

keywords = 'Bella Ciao'
# ddgs_text_gen = ddgs.text(keywords, region='wt-wt', safesearch='Off', timelimit='y')
for r in ddgs_text_gen:
	print(r)
```

the system returned:
```
Traceback (most recent call last):
  File "c:\Users\DESKTOP-AEQ8TK8\Documents\python_projects\duckduckgo_search_test\duckduckgo_test.py", line 8, in <module>
    for r in ddgs_text_gen:
  File "c:\Users\DESKTOP-AEQ8TK8\Documents\python_projects\duckduckgo_search_test\.venv\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 149, in text
    for row in page_data:
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**
search result perhaps?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - duckduckgo_search version 3.1.1

**Additional context**
Run this code and show results, change text() to the function that is causing the problem
```python
import logging
from duckduckgo_search import DDGS

logging.basicConfig(level=logging.DEBUG)

for r in DDGS().text("something"):
    pass
```

Show the same error

**Comment by gambastyle** [comment]
having the exact same problem, this is a big change that causes problems, too cad they deprecated ddg

**Comment by cwyark** [comment]
Same here. Here's what I got:
![image](https://github.com/deedy5/duckduckgo_search/assets/8067533/bdd22fe8-c1dd-44fe-be5d-f46751b1deb3)

**Comment by Trangle** [comment]
same, urllib3 problem?

**Comment by deedy5** [comment]
You get an error because ip is blocked. 
Update to the next version (v3.2.0), DDGS will now raise an exception if requests to the api fail.
If you get a 418 error, either wait 30-60 seconds or use a proxy.
`pip install -U duckduckgo_search`

**Comment by gambastyle** [comment]
Does this mean the IP is blocked? even though I changed it?

**Comment by deedy5** [comment]
what version of duckduckgo_search?

**Comment by deedy5** [comment]
> Does this mean the IP is blocked? even though I changed it?
> 
> DEBUG:urllib3.connectionpool:Resetting dropped connection: duckduckgo.com DEBUG:urllib3.connectionpool:https://duckduckgo.com:443 "POST / HTTP/1.1" 200 None DEBUG:urllib3.connectionpool:Resetting dropped connection: links.duckduckgo.com DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None DEBUG:urllib3.connectionpool:https://links.duckduckgo.com:443 "GET /d.js?q=Bella+Ciao&l=wt-wt&p=-1&s=0&o=json&vqd=4-302527945490078313534260298757318189464 HTTP/1.1" 202 None

Yes, you are right. After a certain number of requests, the status code changes to 202, going to 418. I'll make a patch.

**Comment by gambastyle** [comment]
I updated to 3.4.1 now getting this issue
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://html.duckduckgo.com/html

**Comment by deedy5** [comment]
[link](https://github.com/deedy5/duckduckgo_search#1-text---text-search-by-by-duckduckgocom)
WARNING!: Since version v3.4.0, api requests have been replaced by html parsing. Set a delay of at least 1 second between function calls.
